# Generated by Django 3.2 on 2021-06-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Ticket.ticketquestion', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='ticketanswer',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Ticket.ticket', verbose_name='تیکت'),
        ),
        migrations.AlterField(
            model_name='ticketquestion',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Ticket.ticket', verbose_name='تیکت'),
        ),
    ]
